server:
  port: 8081

spring:
  application:
    name: WeatherPublisher
  config:
    import: optional:configserver:http://localhost:9000
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 2000
        max-attempts: 3
        max-interval: 3000
      username: centralConfig
      password: 2Ski!1C5#2oG
